service: test-two
frameworkVersion: '>=1.1.0'
plugins:
  - serverless-offline
  - serverless-apigw-binary
package:
  individually: true
  excludeDevDependencies: false
provider:
  name: aws
  region: us-west-1
  runtime: nodejs16.x
  memorySize: 192
  timeout: 10
custom:
  serverless-offline:
    httpPort: 3000
  apigwBinary:
    types:
      - '*/*'
functions:
  web-app:
    handler: handler.webApp
    events:
      - http: ANY {proxy+}
      - http: ANY /
