# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1
orbs:
  nx: nrwl/nx@1.5.0
jobs:
  build:
    docker:
      - image: 'cimg/node:16.15.1'
    steps:
      - checkout
      - run:
          command: yarn install --frozen-lockfile
          name: Install dependencies
      - nx/set-shas
      - run:
          command: >-
            yarn nx affected --target=build --base=$NX_BASE --parallel
            --max-parallel=3
          name: Run Builds
  test:
    docker:
      - image: 'cimg/node:16.15.1'
    steps:
      - checkout
      - nx/set-shas
      - run:
          command: >-
            yarn nx affected --target=test --base=$NX_BASE --parallel
            --max-parallel=2
          name: Run Tests
  lint:
    docker:
      - image: 'cimg/node:16.15.1'
    steps:
      - checkout
      - nx/set-shas
      - run:
          command: >-
            yarn nx affected --target=lint --base=$NX_BASE --parallel
            --max-parallel=2
          name: Run Tests

workflows:
  version: 2
  ci:
    jobs:
      - build
      - test:
          requires:
            - build
      - lint:
          requires:
            - build
