org: hacksc
app: <%= name %>
service: <%= name %>
plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: <%= packageName %>/app.app
    packRequirements: false
package:
  individually: false
  patterns:
    - '!**'
    - '<%= packageName %>/**'
provider:
  name: aws
  runtime: python3.9
  region: us-west-1
functions:
  api:
    handler: wsgi_handler.handler
    # environment: ${file(configs/env.${opt:stage,'local'}.yml)}
    events:
      - http: ANY /
      - http: ANY /{proxy+}
