## Compose file for staging environment (used by Release to create ephemeral environment for preview)
version: '3'

services:
  app:
    build: .
    container_name: ${APP_CONTAINER_NAME}
    command: yarn serve:staging
    env_file:
      - .env.staging
    ports:
      - ${PORT}:${PORT}
