org: hacksc
app: myproject
service: myproject
plugins:
  - serverless-python-requirements
  - serverless-wsgi
  - serverless-domain-manager
custom:
  wsgi:
    app: myproject/app.app
    packRequirements: false
  customDomain:
    domainName: <registered_dmain_name>
    basePath: ''
    stage: ${self:provider.stage}
    createRoute53Record: true
package:
  individually: false
  patterns:
    - '!**'
    - 'myproject/**'
provider:
  name: aws
  runtime: python3.9
  region: us-west-1
functions:
  api:
    handler: wsgi_handler.handler
    environment: ${file(configs/env.${opt:stage,'local'}.yml)}
    events:
      - http: ANY /
      - http: ANY /{proxy+}
