org: hacksc
app: myproject
service: myproject
plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: myproject/app.app
    packRequirements: false
package:
  individually: false
  patterns:
    - '!**'
    - 'myproject/**'
provider:
  name: aws
  runtime: python3.9
  region: us-west-1
functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}
