org: hacksc
app: onboarding-api
service: onboarding-api
plugins:
  - serverless-python-requirements
  - serverless-wsgi
custom:
  wsgi:
    app: onboarding_api/app.app
    packRequirements: false
package:
  individually: false
  patterns:
    - '!**'
    - 'onboarding_api/**'
provider:
  name: aws
  runtime: python3.9
  region: us-west-1
functions:
  api:
    handler: wsgi_handler.handler
    # environment: ${file(configs/env.${opt:stage,'local'}.yml)}
    events:
      - http: ANY /
      - http: ANY /{proxy+}
