create table "public"."company_saved_user_profiles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "user_id" uuid,
    "company_id" uuid,
    "saved" boolean not null
);


alter table "public"."company_saved_user_profiles" enable row level security;

CREATE UNIQUE INDEX company_saved_user_profiles_pkey ON public.company_saved_user_profiles USING btree (id);

alter table "public"."company_saved_user_profiles" add constraint "company_saved_user_profiles_pkey" PRIMARY KEY using index "company_saved_user_profiles_pkey";

alter table "public"."company_saved_user_profiles" add constraint "company_saved_user_profiles_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies(id) not valid;

alter table "public"."company_saved_user_profiles" validate constraint "company_saved_user_profiles_company_id_fkey";

alter table "public"."company_saved_user_profiles" add constraint "company_saved_user_profiles_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_profiles(user_id) not valid;

alter table "public"."company_saved_user_profiles" validate constraint "company_saved_user_profiles_user_id_fkey";


