create table "public"."company_saved_participants" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "user_id" uuid not null,
    "company_id" uuid not null,
    "saved" boolean not null
);


alter table "public"."company_saved_participants" enable row level security;

CREATE UNIQUE INDEX company_saved_participants_pkey ON public.company_saved_participants USING btree (id);

alter table "public"."company_saved_participants" add constraint "company_saved_participants_pkey" PRIMARY KEY using index "company_saved_participants_pkey";

alter table "public"."company_saved_participants" add constraint "company_saved_participants_company_id_fkey" FOREIGN KEY (company_id) REFERENCES companies(id) not valid;

alter table "public"."company_saved_participants" validate constraint "company_saved_participants_company_id_fkey";

alter table "public"."company_saved_participants" add constraint "company_saved_participants_user_id_fkey" FOREIGN KEY (user_id) REFERENCES participants(id) not valid;

alter table "public"."company_saved_participants" validate constraint "company_saved_participants_user_id_fkey";


