-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.bonus_points
(
    id uuid NOT NULL,
    name character varying COLLATE pg_catalog."default" NOT NULL,
    points integer NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT bonus_points_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.bonus_points
    OWNER to postgres;

ALTER TABLE IF EXISTS public.bonus_points
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.bonus_point_status
(
    id integer NOT NULL,
    status character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT bonus_point_status_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.bonus_point_status
    OWNER to postgres;

ALTER TABLE IF EXISTS public.bonus_point_status
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.bonus_points_log
(
    log_id uuid NOT NULL,
    user_id uuid NOT NULL,
    bonus_points_id uuid NOT NULL,
    status integer NOT NULL DEFAULT 0,
    "timestamp" timestamp with time zone DEFAULT now(),
    CONSTRAINT bonus_points_log_pkey PRIMARY KEY (log_id),
    CONSTRAINT bonus_points_log_bonus_points_id_fkey FOREIGN KEY (bonus_points_id)
        REFERENCES public.bonus_points (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT bonus_points_log_status_fkey FOREIGN KEY (status)
        REFERENCES public.bonus_point_status (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT bonus_points_log_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.bonus_points_log
    OWNER to postgres;

ALTER TABLE IF EXISTS public.bonus_points_log
    ENABLE ROW LEVEL SECURITY;
