create table "public"."application_status" (
    "id" integer generated by default as identity not null,
    "status" character varying
);


alter table "public"."application_status" enable row level security;

alter table "public"."user_profiles" add column "application_status" integer not null default 1;

CREATE UNIQUE INDEX application_status_pkey ON public.application_status USING btree (id);

alter table "public"."application_status" add constraint "application_status_pkey" PRIMARY KEY using index "application_status_pkey";

alter table "public"."user_profiles" add constraint "user_profiles_application_status_fkey" FOREIGN KEY (application_status) REFERENCES application_status(id) not valid;

alter table "public"."user_profiles" validate constraint "user_profiles_application_status_fkey";