-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.user_profiles
    ADD COLUMN email character varying COLLATE pg_catalog."default" NOT NULL;
ALTER TABLE IF EXISTS public.user_profiles
    ADD CONSTRAINT user_profiles_email_key UNIQUE (email);

CREATE POLICY "Enable all for users based on user_id"
    ON public.user_profiles
    AS PERMISSIVE
    FOR ALL
    TO anon, authenticated
    USING ((auth.uid() = user_id))
    WITH CHECK ((auth.uid() = user_id));
