-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.user_profiles
    RENAME created_at TO user_id;

ALTER TABLE public.user_profiles
    ALTER COLUMN user_id TYPE uuid;
ALTER TABLE IF EXISTS public.user_profiles
    ALTER COLUMN user_id DROP DEFAULT;

ALTER TABLE IF EXISTS public.user_profiles
    ALTER COLUMN user_id SET NOT NULL;

ALTER TABLE IF EXISTS public.user_profiles
    ADD CONSTRAINT user_profiles_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
