-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE TABLE IF NOT EXISTS public.event_log
(
    log_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id uuid NOT NULL,
    event_id bigint NOT NULL,
    check_in_time timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT event_log_pkey PRIMARY KEY (log_id),
    CONSTRAINT event_log_event_id_fkey FOREIGN KEY (event_id)
        REFERENCES public.events (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION,
    CONSTRAINT event_log_user_id_fkey FOREIGN KEY (user_id)
        REFERENCES auth.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.event_log
    OWNER to postgres;

ALTER TABLE IF EXISTS public.event_log
    ENABLE ROW LEVEL SECURITY;

ALTER TABLE IF EXISTS public.events
    ADD COLUMN points integer NOT NULL;
