create table "public"."events" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "name" character varying not null,
    "description" text,
    "start" timestamp with time zone not null,
    "end" timestamp with time zone not null,
    "location" character varying not null
);


alter table "public"."events" enable row level security;

CREATE UNIQUE INDEX events_pkey ON public.events USING btree (id);

alter table "public"."events" add constraint "events_pkey" PRIMARY KEY using index "events_pkey";


create table "public"."pinned_events" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "user_id" uuid not null,
    "event_id" bigint not null
);


alter table "public"."pinned_events" enable row level security;

CREATE UNIQUE INDEX pinned_events_pkey ON public.pinned_events USING btree (id);

alter table "public"."pinned_events" add constraint "pinned_events_pkey" PRIMARY KEY using index "pinned_events_pkey";

alter table "public"."pinned_events" add constraint "pinned_events_event_id_fkey" FOREIGN KEY (event_id) REFERENCES events(id) not valid;

alter table "public"."pinned_events" validate constraint "pinned_events_event_id_fkey";

alter table "public"."pinned_events" add constraint "pinned_events_user_id_fkey" FOREIGN KEY (user_id) REFERENCES user_profiles(user_id) not valid;

alter table "public"."pinned_events" validate constraint "pinned_events_user_id_fkey";