create table "public"."pointr_shortlinks" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "path" character varying not null,
    "url" text not null
);

CREATE UNIQUE INDEX pointr_shortlinks_path_key ON public.pointr_shortlinks USING btree (path);
CREATE UNIQUE INDEX pointr_shortlinks_pkey ON public.pointr_shortlinks USING btree (id);
ALTER TABLE "public"."pointr_shortlinks" ADD CONSTRAINT "pointr_shortlinks_pkey" PRIMARY KEY using index "pointr_shortlinks_pkey";
ALTER TABLE "public"."pointr_shortlinks" ADD CONSTRAINT "pointr_shortlinks_path_key" UNIQUE using index "pointr_shortlinks_path_key";