#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

staged=$(git diff --name-only --staged --diff-filter=d)
export NIXPKGS_ALLOW_INSECURE=1
nix develop --impure \
  --extra-experimental-features nix-command \
  --extra-experimental-features flakes \
  --command bash -c "yarn format && pre-commit run --all-files"
git add ${staged}
