#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

staged=$(git diff --name-only --staged --diff-filter=d)
nix develop --command bash -c "yarn format && pre-commit run --all-files"
git add ${staged}
