name: CI on Supabase migration scripts

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0
      - name: Verify migration works fine
      - run: supabase start
