name: CI on Supabase migration scripts

on:
  push:
    paths:
      - 'supabase/migrations/**'
  pull_request:
    paths:
      - 'supabase/migrations/**'
  workflow_dispatch:

jobs:
  supabase-migration-test:
    runs-on: ubuntu-22.04
    name: Verify migration works fine
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0
      - run: supabase start
