name: CI on affected monorepo apps code

on: [push, workflow_dispatch]

jobs:
  prepare:
    name: Setup yarn
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
  build:
    name: Build affected apps
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn nx affected --target=build --parallel
  test:
    name: Test affected apps
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn nx affected --target=test --parallel
  lint:
    name: Lint affected apps
    runs-on: ubuntu-latest
    needs: prepare
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn nx affected --target=lint --parallel
